AgendaElectronica/Controllers/ContactosController.cs
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using AgendaElectronica.Core.DTOs;
using AgendaElectronica.Core.Models;
using AgendaElectronica.Core.Services;
using AgendaElectronica.Models;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AgendaElectronica.Controllers
{
    public class ContactosController:Controller
    {
        private readonly IContactosService _contactosService;
        private readonly IMapper _mapper;

        public ContactosController(IContactosService contactosService,
            IMapper mapper)
        {
            _contactosService = contactosService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            //Recupero la lista de contactos del usuario logueado o del usuario autenticado
            List<Contacto> contactos =
                _contactosService.GetContactos(User.Identity.IsAuthenticated ? User.Identity.Name : "anon");
            return View(contactos);
        }

        public IActionResult CrearEditar(int codigo = 0)
        {
            Contacto contacto = codigo == 0 ? new Contacto() : _contactosService.GetContacto(codigo);

            GuardarContactoVm guardarContacto = _mapper.Map<GuardarContactoVm>(contacto);
            return View(guardarContacto);
        }

        [HttpPost]
        public IActionResult GuardarContacto(GuardarContactoVm guardarContacto)
        {
            CrearEditarContactoDto crearEditarContacto = new CrearEditarContactoDto()
            {
                IdUsuario = User.Identity.IsAuthenticated ? User.Identity.Name : "anon",
                Codigo = guardarContacto.Codigo ?? 0,
                Nombres = guardarContacto.Nombre,
                Apellidos = guardarContacto.Apellido,
                Email = guardarContacto.Email,
                TelMovil = guardarContacto.TelefonoMovil,
                Direccion = guardarContacto.Direccion,
                TelTrabajo = guardarContacto.TelefonoTrabajo
            };

            //Dependiendo de si estamos creando o editanto
            Contacto contacto = guardarContacto.Codigo == null || guardarContacto.Codigo.Value == 0
                ? _contactosService.CrearContacto(crearEditarContacto)
                : _contactosService.EditarContacto(crearEditarContacto);


            if (guardarContacto.Imagen != null)
            {
                using (MemoryStream ms = new MemoryStream())
                {
                    guardarContacto.Imagen.CopyTo(ms);

                    Multimedia multimedia = new Multimedia()
                    {
                        Archivo = ms.ToArray(),
                        Extension = Path.GetExtension(guardarContacto.Imagen.FileName),
                        MimeType = guardarContacto.Imagen.ContentType,
                        NombreArchivo = guardarContacto.Imagen.FileName
                    };

                    _contactosService.AgregarImagenContacto(contacto.Codigo, multimedia);

                }
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult EliminarContacto(int idContacto)
        {
            _contactosService.EliminarContacto(idContacto, User.Identity.IsAuthenticated ? User.Identity.Name : "anon");
            return RedirectToAction("Index");
        }

        public IActionResult GetUrlImagen(int idMultimedia)
        {
            Multimedia multimedia = _contactosService.GetMultimedia(idMultimedia);

            return multimedia == null ? null : File(multimedia.Archivo, multimedia.MimeType);
        }
    }   
}

AgendaElectronica/Views/Contactos/CrearEditar.cshtml
@model GuardarContactoVm
@{
    ViewData["Title"] = "Crear Editar Contactos";
}

<div class="container-fluid" title="Formulario de Crear Editar Contactos" role="heading">
    <div class="row">
        <div class="offset-3 col-md-6">
            <div class="card ">
                <div class="card-header card-header-rose card-header-icon">
                    
                    <h4 class="card-title">@(Model.Codigo == null || Model.Codigo.Value == 0 ? "Nuevo contacto":"Editar contacto")</h4>
                </div>
                <div class="card-body" role="form">
                    <p class="text-danger" title="Todos los campos con asteriscos son requeridos" aria-label="Todos los campos con astericos son requeridos"><strong>Todos los campos con (*) son requeridos</strong></p>
                    <form asp-controller="Contactos" asp-action="GuardarContacto" id="frmGuardarContacto" enctype="multipart/form-data">
                        <fieldset>
                            <div class="form-group">
                                <label asp-for="Nombre" class="label text-danger">Nombre (*)</label>
                                <br />
                                <input asp-for="Nombre" type="text" class="form-control" title="Nombre contacto" aria-label="Nombre contacto" aria-labelledby="btnGuardarContact" aria-required="true">
                            </div>
                            <div class="form-group">
                                <label asp-for="Apellido" class="label text-danger">Apellido (*)</label>
                                <br />
                                <input asp-for="Apellido" class="form-control" title="Apellido Contacto" aria-label="Apellido Contacto" aria-labelledby="btnGuardarContact" aria-required="true">
                            </div>
                            <div class="form-group">
                                <label asp-for="Email" class="label">Email</label>
                                <br />
                                <input asp-for="Email" type="email" class="form-control" title="Email contacto" aria-label="Email contacto" aria-labelledby="btnGuardarContact">
                            </div>
                            <div class="form-group">
                                <label asp-for="TelefonoMovil" class="label">Telefono movil</label>
                                <br />
                                <input asp-for="TelefonoMovil" class="form-control" title="Celular contacto" aria-label="Celular contacto" aria-labelledby="btnGuardarContact">
                            </div>
                            <div class="form-group">
                                <label asp-for="TelefonoTrabajo" class="label">Telefono Trabajo</label>
                                <br />
                                <input asp-for="TelefonoTrabajo" class="form-control" title="Teléfono trabajo contacto" aria-label="Teléfono trabajo contacto" aria-labelledby="btnGuardarContact">
                            </div>
                            <div class="form-group">
                                <label asp-for="Direccion" class="label">Direccion</label> <br />
                                <br />
                                <textarea asp-for="Direccion" class="form-control" cols="4" rows="5" title="Dirección contacto" aria-label="Dirección contacto" aria-labelledby="btnGuardarContact"></textarea>
                            </div>
                            <label asp-for="Imagen" class="label">Imagen: </label>
                            <br />
                            <input asp-for="Imagen" type="file" title="Seleccione la imagen del contacto" aria-label="Seleccione la imagen del contacto" aria-labelledby="btnGuardarContact">

                            <input asp-for="Codigo" />
                        </fieldset>
                        <button style="display: none" type="submit">Submit</button>
                    </form>
                </div>
                <div class="card-footer ">
                    <button type="submit" class="btn is-filled btn-rose" id="btnGuardarContact" title="Botón Guardar Contacto" aria-label=" Botón Guardar contacto">Guardar</button>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function() {
            $("#btnGuardarContact").on('click', function(e) {
                e.preventDefault();
                $('#frmGuardarContacto').submit();
            });
        });
    </script>
}

AgendaElectronica/Views/Contactos/Index.cshtml
@model List<AgendaElectronica.Core.Models.Contacto>
@{
    ViewData["Title"] = "Contactos";
}


<div class="container-fluid" title="Listado de contactos" role="heading">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-rose card-header-icon">
                    
                    <h4 class="card-title" title="Contactos" aria-label="Contactos">Contactos</h4>
                </div>
                <div class="card-body">
                    <div class="text-left">
                        <button type="button" class="btn btn-success is-filled" id="btnNuevoContact" title="Botón nuevo contacto" aria-label="Botón nuevo contacto">Nuevo</button>
                    </div>
                    <div class="table-responsive" title="Tabla de contactos">
                        <table class="table table-striped" title="Tabla de contactos" aria-label="Tabla de contactos">
                            <caption>Lista de los contactos del usuario</caption>
                            <thead>
                            <tr>

                                <th scope="col" title="Columna nombre contacto" aria-label="Columna nombre contacto" id="tableName">Nombre</th>
                                <th scope="col" title="Columna dirección contacto" aria-label="Columna dirección contacto" id="tableDir">Dirección</th>
                                <th scope="col" title="Columna teléfono contacto" aria-label="Columna teléfono contacto" id="tableTel">Teléfono</th>
                                <th scope="col" title="Columna celular contacto" aria-label="Columna celular contacto" id="tableCel">Celular</th>
                                <th scope="col" title="Columna email contacto" aria-label="Columna email contacto" id="tableMail">Email</th>
                                <th scope="col" title="Columna fotografía contacto" aria-label="Columna fotografía contacto" id="tablePic">Fotogrfía</th>
                                <th scope="col" title="Acciones" aria-label="Acciones" class="text-right">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var contacto in Model)
                            {
                                <tr>

                                    <td title="Columna nombre contacto" aria-label="Columna nombre contacto" headers="tableName">@contacto.GetNombreCompleto()</td>
                                    <td title="Columna dirección contacto" aria-label="Columna dirección contacto" headers="tableDir">@contacto.Direccion</td>
                                    <td title="Columna teléfono contacto" aria-label="Columna teléfono contacto" headers="tableTel">
                                        @(string.IsNullOrEmpty(contacto.TelefonoTrabajo) ? "N/A" : contacto.TelefonoTrabajo)
                                    </td>
                                    <td title="Columna celular contacto" aria-label="Columna celular contacto" headers="tableCel">
                                        @(string.IsNullOrEmpty(contacto.TelefonoMovil) ? "N/A" : contacto.TelefonoMovil)
                                    </td>
                                    <td title="Columna email contacto" aria-label="Columna email contacto" headers="tableMail">
                                        @(string.IsNullOrEmpty(contacto.Email) ? "N/A" : contacto.Email)
                                    </td>
                                    <td title="Columna fotografía contacto" aria-label="Columna fotografía contacto" headers="tablePic">
                                        @if (contacto.IdMultimedia == null || contacto.IdMultimedia == 0)
                                        {
                                            <img src="@Url.Content("img/no-image.png")" width="100" height="100" alt="Fotografia por defecto" title="Fotofrafía por defecto"/>
                                        }
                                        else
                                        {
                                            <img src="@Url.Action("GetUrlImagen", new {idMultimedia = contacto.IdMultimedia})" width="100" height="100" alt="Fotografia contacto" title="Fotografia contacto"/>
                                        }

                                    </td>
                                    <td class="td-actions text-right">
                                        <button type="button" title="Editar contacto" aria-label="Editar contacto" class="btn btn-success editContact" data-url="@Url.Action("CrearEditar", new {codigo = contacto.Codigo})">
                                           Editar
                                        </button>
                                        <button type="button" title="Eliminar contacto" aria-label="Eliminar contacto" class="btn btn-danger deleteContact" data-codigo="@contacto.Codigo">
                                           Eliminar
                                        </button>
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form method="post" asp-controller="Contactos" asp-action="EliminarContacto" id="frmDeleteContact" style="display: none;">
    <input type="hidden" id="codeDelete" name="idContacto"/>
    <button type="submit" style="display: none">Submit</button>
</form>

<input type="hidden" id="urlNuevoContact" value="@Url.Action("CrearEditar")"/>

@section scripts
{
    <script>
        $(document).ready(function() {
            $('#btnNuevoContact').on('click', function(e) {
                e.preventDefault();
                var urlObj = $("#urlNuevoContact").val();

                location.href = urlObj;

            });

            $('.editContact').on('click', function(e) {
                e.preventDefault();
                var urlEdit = $(this).data('url');
                location.href = urlEdit;
            });

            $('.deleteContact').on('click', function (e) {
                e.preventDefault();
                var code = $(this).data('codigo');
                $('#codeDelete').val(code);
                $('#frmDeleteContact').submit();
            });
        });
    </script>
}