AgendaElectronica/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AgendaElectronica.Core.Models;
using AgendaElectronica.Core.Services;
using AgendaElectronica.Extensions;
using AgendaElectronica.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AgendaElectronica.Controllers
{
    public class CuentaController : Controller
    {
        private readonly ISeguridadService _seguridadService;
        private readonly IUsuarioService _usuarioService;

        public CuentaController(ISeguridadService seguridadService, 
            IUsuarioService usuarioService)
        {
            _seguridadService = seguridadService;
            _usuarioService = usuarioService;
        }

        public IActionResult Login()
        {

            
            if (TempData["mensaje"] != null)
            {
                ViewBag.mensaje = TempData["mensaje"];
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Loguearse(LoginVm login)
        {
            bool loginValido = _seguridadService.LoginValido(login.NombreUsuario, login.Password);

            if (loginValido)
            {
                Usuario user = _usuarioService.GetUsuario(login.NombreUsuario);
                //Lo logueamos
                List<Claim> claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, user.NombreUsuario),
                    new Claim("FullName", user.NombreCompleto()),
                    new Claim(ClaimTypes.Role, user.IdRol.ToString())
                };

                ClaimsIdentity claimsIdentity =
                    new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                AuthenticationProperties authenticationProperties = new AuthenticationProperties
                {
                    IsPersistent = true
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity), authenticationProperties);


                //Lo mandamos a la lista de sus contactos
                return RedirectToAction("Index", "Contactos");
            }

            //Si el login no es valido, lo mando a la pagina del login nuevamente

            TempData["mensaje"] = "Las credenciales ingresadas no son correctas";

            return RedirectToAction("Login");

        }

        [Authorize]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }
    }
}

AgendaElectronica/Views/Cuenta/Login.cshtml
@model LoginVm
@{
    ViewData["Title"] = "Login";
    Layout = "_LayoutLogin";
}

<div class="col-md-4 col-sm-6 ml-auto mr-auto" role="heading">
    <form class="form" asp-controller="Cuenta" asp-action="Loguearse" title="Formulario de ingreso" aria-label="Formulario de ingreso">
        <div class="card card-login card-hidden">
            <div class="card-header card-header-rose text-center">
                <h1 class="card-title" title="Log In" aria-label="Log In">Log in</h1>
            </div>
            <div class="card-body" role="form">
                <fieldset>
                    
                    <div class="bmd-form-group">
                        <div class="input-group">
                            
                            <input asp-for="NombreUsuario" type="text" class="form-control" placeholder="Usuario" title="Nombre de Usuario" aria-label="Nombre de Usuario" required="required" aria-labelledby="btnIngreso" aria-required="true">
                        </div>
                    </div>
                    <div class="bmd-form-group">
                        <div class="input-group">
                            
                            <input asp-for="Password" type="password" class="form-control" placeholder="Password" title="Contraseña" aria-label="Contraseña" required="required" aria-labelledby="btnIngreso" aria-required="true">
                        </div>
                    </div>
                </fieldset>
            </div>
            <div class="card-footer justify-content-center">
                <button type="submit" class="btn btn-rose btn-link btn-lg" title="Botón ingresar" aria-label="Botón ingresar" id="btnIngreso">Ingresar</button>
            </div>
        </div>
    </form>
</div>

@*<input type="hidden" id="mensajeLog" value="@ViewBag.mensaje"/>*@

@section scripts
{
    <script>
        $(document).ready(function() {
            var mensaje = $("#mensajeLog").val();

            if (mensaje) {
                swal('Espera', mensaje, 'warning');
            }
        });
    </script>
}